version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
